# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('value', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='group', to='main.Parameter'),
        ),
    ]
